backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: 'static/uploads' # Media files will be stored in the repo under static/uploads
public_folder: '/uploads' # The src attribute for uploaded media will begin with /uploads

collections:
  - name: 'portfolio' # Used in routes, e.g., /admin/collections/blog
    label: 'Portfolio' # Used in the UI
    folder: 'src/portfolio/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }

      - label: 'Images'
        name: 'Images',
        widget: 'image'
        media_library: 
          config: 
            multiple: true
        
      - { label: 'Body', name: 'body', widget: 'markdown' }

 - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "src/pages/about/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "markdown"}
          - label: 'Featured Image'
            name: 'featured_image'
            widget: 'image'

      - label: "Price page"
        name: "price_page"
        file: "src/pages/prices/prices.md"
        fields:
          - { label: "Title", name: "title", widget: "string"}
          - label: "Prices"
            name: "prices"
            widget: "list"
            fields: 
              - {label: "Price", name: "price", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
          - label: "Logo Section"
            name: "logo_section"
            widget: "object"
            fields: 
              - {label: "Title", name: "title", widget: "string"}
              - {label: "description", name: "description", widget: "markdown"}
          - label: "Slider"
            name: "slider"
            widget: "object"
            fields: 
              - {label: "Title", name: "title", widget: "string"}
              - {label: "description", name: "description", widget: "markdown"}
              - label: 'Images'
                name: 'Images',
                widget: 'image'
                media_library: 
                  config: 
                    multiple: true